# -*- coding: utf-8 -*-
"""11. 아이리스 데이터셋ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K8-bpF-RrhIw-fXaMyyrBpo4ztCqnJgd

# **1. Iris DataSet**
* 데이터셋: 특정한 작업을 위해 데이터를 관련성 있게 모아놓은 것
* [사이킷런 데이터셋 페이지](https://scikit-learn.org/stable/api/sklearn.datasets.html#module-sklearn.datasets)
"""

from sklearn.datasets import load_iris

iris = load_iris()
# iris

print(iris['DESCR'])

data = iris['data']
# data

target = iris['target']
# target

feature_names = iris['feature_names']
# feature_names

"""* sepal length (cm): 꽃받침의 길이
* sepal width (cm): 꽃받침의 너비
* petal length (cm): 꽃잎의 길이
* petal width (cm): 꽃잎의 너비
"""

import pandas as pd

df_iris = pd.DataFrame(data, columns = feature_names)
df_iris

df_iris['target'] = target
df_iris

target.shape

from sklearn.model_selection import train_test_split

# train_test_split(독립변수, 종속변수, 테스트사이즈, 시드값 ...)
X_train, X_test, y_train, y_test = train_test_split(df_iris.drop('target', axis=1),
                                                    df_iris['target'],
                                                    test_size = 0.2,
                                                    random_state=2024)

X_train.shape, X_test.shape

y_train.shape, y_test.shape

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

svc = SVC()

svc.fit(X_train, y_train)

y_pred = svc.predict(X_test)
y_pred

print('정답률: ', accuracy_score(y_test, y_pred))

# 정답률이 만족스럽지 않기 때문에 데이터를 다시 섞기로 함!!
X_train, X_test, y_train, y_test = train_test_split(df_iris.drop('target', axis=1),
                                                    df_iris['target'],
                                                    test_size = 0.2,
                                                    random_state=2023)

svc.fit(X_train, y_train)

y_pred = svc.predict(X_test)
y_pred

print('정답률: ', accuracy_score(y_test, y_pred))

"""# **2. AI 통합 플랫폼 사이트**

### 2-1. 캐글(Kaggle)
* [캐글](https://kaggle.com)
* 구글에서 운영하는 전세계 AI개발자, 데이터 사이언티스트들이 데이터를 분석하고 토론할 수 있는 자료 등을 제공
* 데이터 분석 및 머신러닝, 딥러닝 대회를 개최
* 다량의 데이터셋, 파이썬 자료, R 자료 등을 제공

### 2-2. 데이콘(Dacon)
* [데이콘](https://dacon.io/)
* 국내 최초 AI 해커톤 플랫폼
* 전문 인력 채용과 학습을 할 수 있는 여러가지 AI 자료 등을 제

### 2-3. AI 허브(AI Hub)
* [AI허브](https://www.aihub.or.kr/)
* 한국지능정보사회진흥원이 운영하는 AI 통합 플랫폼
* AI 기술 및 제품 서비스 개발에 필요한 AI 인프라를 제공
"""

